version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ngrok

  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - web