name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  push_to_packages:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker-compose.yml
          push: true
          tags: docker.pkg.github.com/themaster3558/clashroyale-sfx/clashroyale-sfx:latest
          labels: "com.github.repository=$GITHUB_REPOSITORY"
